#!/bin/sh
set -e

if [ "$1" = "configure" ] && [ -z "$2" ]; then
    echo "─────────────────────────────────────────────"
    echo "Hướng dẫn sau cài đặt:"
    echo "  1. Cấu hình bộ gõ: Chạy fcitx5-configtool để thêm Lotus."
    echo "  2. Bật dịch vụ systemd: sudo systemctl enable --now fcitx5-lotus-server@\$USER.service"
    echo "Các bước bổ sung nếu cần:"
    echo "  - Wayland (KDE/Hyprland): Thiết lập Virtual Keyboard & Permission."
    echo "  - Kanata: Exclude 'Lotus-Uinput-Server' trong cấu hình."
    echo "─────────────────────────────────────────────"
fi

#DEBHELPER#

exit 0
