version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
  disable:
    - gocyclo
  exclusions:
    rules:
      - path: '_test\.go'
        text: "error message to ignore"